### PR TITLE
added callback buttons in `/pin` command

### PR DESCRIPTION
**Pull request by Awesome-RJ**

### CODE REVIEW

**Comment by annihilatorrrr** [comment]
Get that # in returned log msg, easy to find ree

**Comment by Awesome-RJ** [comment]
i see

**Comment by Awesome-RJ** [comment]
I will put it back also in cutiepii

**Comment by MoeZilla** [comment]
Yes

**Comment by MoeZilla** [comment]
> I will put it back also in cutiepii

I see you are also making a pull request to other people's things.

https://github.com/aryazakaria01/Natsunagi-Nagisa/blob/master/Natsunagi/modules/admin.py#L586

**Comment by Awesome-RJ** [comment]
owo! pro you are man, you made this world.

that's open-source... any person can use. I just pulled it.. simple

**Comment by annihilatorrrr** [comment]
@Awesome-RJ

**Pull request merged**
